# Generated by Django 4.2 on 2023-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocine_pig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarusuario',
            name='dni',
            field=models.IntegerField(null=True, verbose_name='DNI: '),
        ),
        migrations.AddField(
            model_name='registrarusuario',
            name='fecha_De_Nacimiento',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='registrarusuario',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='apellido',
            field=models.CharField(max_length=128, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='mail',
            field=models.EmailField(max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
    ]
