# Generated by Django 4.2 on 2023-05-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocine_pig', '0002_registrarusuario_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('registrar_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocine_pig.registrarusuario')),
            ],
        ),
    ]
