# Generated by Django 4.2 on 2023-05-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocine_pig', '0004_rename_fecha_de_nacimiento_registrarusuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Titulo')),
                ('director', models.CharField(max_length=128, verbose_name='Director')),
                ('actor_ppl', models.CharField(max_length=128, verbose_name='Actor Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Complejo')),
                ('direccion', models.CharField(max_length=256, verbose_name='Direccion')),
                ('peliculas', models.ManyToManyField(related_name='Peliculas', to='autocine_pig.pelicula')),
            ],
        ),
    ]
