# Generated by Django 4.2 on 2023-05-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocine_pig', '0006_alter_registrarusuario_fecha_de_nacimiento'),
        ('autocine_pig', '0006_alter_registrarusuario_fecha_de_nacimiento_valor'),
    ]

    operations = [
    ]
