# Generated by Django 4.2.1 on 2023-06-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocine_pig', '0006_alter_registrarusuario_fecha_de_nacimiento_valor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valor',
            new_name='Valore',
        ),
    ]
